### ISSUE TITLE
Can you check if keepawake is active or not?

### ISSUE THREAD

**Issue by msacchetti** [capacitor-community/keep-awake#16]
I am firing off keepawake with a component lifecycle hook, (i.e. viewDidEnter) and i dont want to keep firing it every time the component mounts if it is already active. is there any way to check for this? i.e: isKeptAwake, or willAllowSleep, etc?

**Comment by robingenz** [comment]
Currently there is no way to check this.
In your case, a method to check would not be very useful, since it would still be necessary to make a request to the plugin each time, and a second request if it is not active.
For other use cases, however, such a method would certainly be helpful.
I've created a feature request: #17
